### ISSUE TITLE
A few remarks

### ISSUE THREAD

**Issue by Jeroen-G** [garygreen/pretty-routes#3]
A few remarks:
- Don't require laravel/framework, composer warns about it, you would not want to end up with 2 installations of the framework. Require laravel/support instead. Or neither, since it wouldn't make sense running it outside Laravel.
- Although it works, you package namespace lacks a vendor. For example, Laravel's components are Illuminate\Auth or Illuminate\Database. This allows for the existence of other Auth and Database classes next to each other. Instead of a Vendor\Package\Class namespace, you have a Package\Class namespace. Better would be something like GaryGreen\PrettyRoutes\_Classname_
- Why do you use middleware to overrule a request instead of providing a route and controller? With a route, a user could add additional middleware (such as authorization, I don't want everyone to see the routes).
- If you use something like StyleCI with the Laravel preset, your code will be styled the same as the Laravel codebase, which looks pretty.

**Comment by garygreen** [comment]
Woah, thanks for the feedback man, much appreciated :+1: 

> Don't require laravel/framework, composer warns about it. Require laravel/support instead. 

Although requiring `laravel/support` is common it doesn't make much sense, as you can install `laravel/support` in a non-laravel application, and the package would install fine but not work because it requires full laravel framework. I'm not sure in what cases it would try and install two versions of Laravel? I actually don't see the composer warning about it when installing...maybe I am on a different version of composer or seeing something different?

> Although it works, you package namespace lacks a vendor

It's probably a good idea to have a vendor in the namespace but [psr-4 doesn't require it](http://www.php-fig.org/psr/psr-4/). I kinda find it weird having your username as a vendor so opted to just keep the vendor as "PrettyRoutes". It works for Laravel because Taylor has coined "Illuminate" - it would be strange to have the framework "TaylorOtwell\Foundation\Application" :laughing: 

> Why do you use middleware

I'm sure there was a reason I did this, I think it was to do with a problem where my app was adding a wildcard route and it was overriding the one registered in this package, so I switched to using a middleware. I don't think this would be a problem if the service provider is registered before your apps `RouteServiceProvider`, will check and try and change it to use the router instead, which would be better.

> Use something like StyleCI with the Laravel preset, your code will be styled the same as the Laravel codebase, which looks pretty.

I'm kinda torn on this, when Laravel switched from PSR-4 to PSR-2 I shed a slight tear because I'm not really a fan of spaces for code indenting. I also prefer the more "spacious" nature of the code style of PSR-4 where brackets are generally on their own lines, I find it easier to read. Of course that's just a personal choice, I am open to switching to PSR-2 as it would make sense to stick to the standard Laravel follows. It'll just take some getting used to :grimacing:

**Comment by Jeroen-G** [comment]
Composer warns me that requiring laravel/framework shouldn't be done because it is a root package of some sort. It does continue with installing your package, but it would look nicer without the warning. I agree that requiring support does not make much sense, but neither does framework. It is just a way of enforcing certain versions of Laravel. If you require support version 5.2, then people know instantly it would not work on 5.3

You don't necessarily need to use your username, anything will work.

As long as routes are properly ordered, it is more of an advantage than a disadvantage. You don't need to register it with the RouteServiceProvider, look in the docs on packages to see that you can just use an include statement. I don't think middleware is designed for this, and as I said it limits the ability to build on your package.

StyleCI can be configured however you want, the presets can also act as a sort of base. This would be helpful when you get Pull Requests.

**Comment by ericlbarnes** [comment]
> Why do you use middleware to overrule a request instead of providing a route and controller? With a route, a user could add additional middleware (such as authorization, I don't want everyone to see the routes).

I noticed this too when I was looking at this package. It seems to me that having the routes public like this could gives attackers way more than you would want. 

Even just an `env` config flag to turn on/off could be an option.

**Comment by garygreen** [comment]
@ericbarnes thanks for your comments. The package does check to see if the app is in debug mode and if it isn't it won't even register the middleware which catches the route. I think an env option isn't really needed imo.

As for why I used a middleware rather than a route, I think there was a reason for it but can't remember now. I do plan on changing it to a proper route though :)

**Comment by ericlbarnes** [comment]
Thanks! I missed that when I was originally looking.

**Comment by AshMenhennett** [comment]
@garygreen is it possible to only show custom routes? I.e is there an option to disable showing the generic Auth routes (login, logout, register and password/*)?

This would be nice for a quick rundown of an app's main routes, I think I would find it helpful :)

Here is a screen after removing the generic routes.
![capture](https://cloud.githubusercontent.com/assets/9494635/21078251/3b477af2-bfb8-11e6-8882-f7dbcceaf167.PNG)

**Comment by tnorthcutt** [comment]
Changing from a middleware to a proper route should allow for easier filtering, e.g. `/routes/{routePrefix}` could only show routes starting with `routePrefix`.

**Comment by judgej** [comment]
On the note about the routes only showing in debug mode, it may be an idea to put that into the readme, because it is a pretty important point when making a decision about whether to install this package.

**Comment by garygreen** [comment]
> On the note about the routes only showing in debug mode, it may be an idea to put that into the readme, because it is a pretty important point when making a decision about whether to install this package.

I would actually recommend to install the package as a dev dependency, and then register it manually in your `AppServiceProvider` if in local environment. I've tried to not over complicate the installation instructions so I've left it down to the developer to determine how it should be installed with the knowledge that the package is already secure "as is".

Take for instance [debugbar](barryvdh/laravel-debugbar) that recommends to install as non-dev, but I would never do so, even though internally it has it's own way of toggling it on/off. Same for filp/whoops - never install it as a non-dev dependency as it could expose env information. Anyway, I digress! 😄

**Comment by judgej** [comment]
A great digress. I'm checking all sorts now.
